apiVersion: v1
kind: Service
metadata:
  name: camel-weather-poc
  labels:
    app: camel-weather-poc
spec:
  type: NodePort
  selector:
    app: camel-weather-poc
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
